### ISSUE TITLE
OPA/Rego入門: クエリの説明に途切れた文がある

### ISSUE THREAD

**Issue by neglect-yp** [m-mizutani/zenn.dev#4]
> ただし、結果判定に必要なデータ（例えば評価対象であるリクエストの構造化データ）は `input` によって渡すことを想定されており、現実的には都度クエリを変更しながら利用する、というユースケースは筆者視点だとあまりおもいつきませんでした。どちらかというと大量の
>
> 具体的な利用場面としてはOPAの`eval`コマンドや`run`コマンドのインタラクティブモードでの入力で使用します。
> https://github.com/m-mizutani/zenn.dev/blob/f935d1a4c9095b64c9e9899f540f1ed41f5dcd93/books/d2f1440cfbba94/rego-package.md?plain=1#L82

となっており、 `どちらかというと大量の` の部分が不完全な文となってしまっていそうです。

**Comment by m-mizutani** [comment]
@neglect-yp お知らせありがとうございます！ 3916fe2 で修正させてもらいました
